# prepare installation
- name: rm -rf /data/rocketmq for second installation
  shell: rm -rf /data/rocketmq

# download rocketmq  
- name: Download rocketmq
  unarchive:
    src: "{{rocketmq_download_url}}"
    dest: /data
    remote_src: yes
    mode: 0750

- name: Rename dir name and Setting environment
  shell: |
    cd /data; if [ ! -d "rocketmq" ]; then mv rocketmq-* rocketmq; fi

- name: Change runserver.sh file to reduce the default Java runtime memory
  lineinfile:
    dest: /data/rocketmq/bin/runserver.sh
    regexp: '.* -server -Xms4g -Xmx4g -Xmn2g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m.*'
    line: 'JAVA_OPT="${JAVA_OPT} -server -Xms256m -Xmx256m -Xmn125m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m"'
    backrefs: yes 

- name: Change runbroker.sh file to reduce the default Java runtime memory
  lineinfile:
    dest:  /data/rocketmq/bin/runbroker.sh
    regexp: '.* -server -Xms8g -Xmx8g -Xmn4g.*'
    line:  'JAVA_OPT="${JAVA_OPT} -server -Xms256m -Xmx256m -Xmn125m"'
    backrefs: yes   

- name: Change sh to bash,ubuntu default shell is dash,Syntax not supported
  replace:
    path: /data/rocketmq/bin/mqnamesrv
    regexp: "^sh.*$"
    replace: "bash ${ROCKETMQ_HOME}/bin/runserver.sh org.apache.rocketmq.namesrv.NamesrvStartup $@"
  when: ansible_os_family == "Debian"
  
- name: Configuration RocketMQ Name Server
  copy:
    src: mqnamesrv.service
    dest: '/lib/systemd/system/mqnamesrv.service'

- name: Configuration RocketMQ Broker Server
  copy:
    src: mqbroker.service
    dest: '/lib/systemd/system/mqbroker.service'

- name: Start and Enable  RocketMQ Name Server
  service:
    name: mqnamesrv
    state: started 
    enabled: yes

- name: Start and Enable  RocketMQ Broker Server
  service:
    name: mqbroker
    state: started
    enabled: yes

- name: sleep 20s,Wait service started,create log file
  shell: sleep 20

- name: Create link  
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /data/rocketmq/bin/mqadmin,dest: /usr/bin/mqadmin}
    - {src: '{{ansible_env.HOME}}/logs/rocketmqlogs/',dest: /data/rocketmq/logs}
    - {src: '{{ansible_env.HOME}}/logs/rocketmqlogs/',dest: /data/logs/rocketmq}
    - {src: /data/rocketmq/conf/,dest: /data/config/rocketmq}
    - {src: /data/rocketmq/bin/runserver.sh,dest: /data/config/rocketmq/runserver.sh}
    - {src: /data/rocketmq/bin/runbroker.sh,dest: /data/config/rocketmq/runbroker.sh}

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check RocketMQ Version
    shell: sudo echo "rocketmq version:" $(ls /data/rocketmq/lib |grep rocketmq-broker |cut -d- -f3) |sudo tee -a /data/logs/install_version.txt

# check service state
- name: Check mqnamesrv Service
  shell: systemctl status mqnamesrv | grep Active*
  register: check_mqnamesrv_service
  notify: check_mqnamesrv_service

- name: Check mqbroker Service
  shell: systemctl status mqbroker | grep Active*
  register: check_mqbroker_service
  notify: check_mqbroker_service


